# Generated by Django 4.1.7 on 2023-03-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference_No', models.CharField(max_length=8)),
                ('Serial_No', models.CharField(max_length=20)),
                ('CMDB_item_type', models.CharField(max_length=20)),
                ('User_name', models.CharField(max_length=50)),
                ('Email_address', models.EmailField(max_length=254, verbose_name=50)),
                ('Organisation', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'tblemployee',
            },
        ),
    ]
